#!/usr/bin/env python3
"""Generate harness/DASHBOARD.md — a project health snapshot.

Stdlib only (no third-party imports). Safe to run anytime; tolerant of missing files.
Reads: VERSION, CHANGELOG.md (top entry), harness/TODOS.md (P0-P3 counts),
the newest harness/logs/activity-*.md, and docs/plans/INDEX.md (optional).
Writes: harness/DASHBOARD.md (never hand-edit that file).

Idempotent: rewrites the file only when its non-timestamp content actually changes.
A no-op run leaves the file (and its "Generated:" timestamp) untouched, so repeated
session-open / hook runs never churn the working tree. See gates/README.md
"Generated-artifact lifecycle". Invoke via your project venv interpreter, never a bare
`python3` that may resolve to an old system Python (e.g. macOS 3.9 ImportErrors on
`datetime.UTC` and the step fails silently).
"""
import os
import re
import glob
import datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Idempotency guard: "- Generated: <timestamp>" is the only volatile line. Normalize it
# before comparing so a substantively-unchanged regeneration is a true no-op (no write,
# no working-tree dirt). Lesson hardened across two production projects.
_GENERATED_LINE_RE = re.compile(r"^- Generated: .*$", re.MULTILINE)


def _content_signature(text):
    return _GENERATED_LINE_RE.sub("- Generated: <ts>", text)


def _write_if_changed(path, new_content):
    """Write only when non-timestamp content changed. Returns True if written."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
    except OSError:
        existing = None
    if existing is not None and _content_signature(existing) == _content_signature(
        new_content
    ):
        return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_content)
    return True


def read(path):
    p = os.path.join(ROOT, path)
    try:
        with open(p, "r", encoding="utf-8") as f:
            return f.read()
    except OSError:
        return ""


def version():
    v = read("VERSION").strip()
    return v or "(no VERSION file)"


def latest_changelog_entry():
    text = read("CHANGELOG.md")
    if not text:
        return "(no CHANGELOG.md)"
    lines = text.splitlines()
    out = []
    started = False
    for ln in lines:
        if ln.startswith("## "):
            if started:
                break
            started = True
        if started:
            out.append(ln)
    return "\n".join(out[:12]).strip() or "(no entries yet)"


def todo_counts():
    text = read("harness/TODOS.md")
    counts = {"P0": 0, "P1": 0, "P2": 0, "P3": 0}
    current = None
    for ln in text.splitlines():
        m = re.match(r"##\s*(P[0-3])", ln)
        if m:
            current = m.group(1)
            continue
        if current and re.match(r"\s*-\s*\[ \]", ln):
            counts[current] += 1
    return counts


def latest_activity():
    files = sorted(glob.glob(os.path.join(ROOT, "harness", "logs", "activity-*.md")))
    if not files:
        return "(no activity log yet)"
    text = ""
    try:
        with open(files[-1], "r", encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return "(unreadable)"
    entries = [ln for ln in text.splitlines() if ln.startswith("### ")]
    head = "\n".join("  " + e[4:] for e in entries[:5])
    return head or "(no entries)"


def plan_counts():
    text = read("docs/plans/INDEX.md")
    if not text:
        return None
    active = len(re.findall(r"\bactive\b", text, re.IGNORECASE))
    completed = len(re.findall(r"\bcompleted\b", text, re.IGNORECASE))
    return active, completed


def main():
    c = todo_counts()
    pc = plan_counts()
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []
    lines.append("# Dashboard")
    lines.append("")
    lines.append("> Auto-generated by `harness/scripts/build_dashboard.py`. Do not hand-edit.")
    lines.append("")
    lines.append("- Generated: " + now)
    lines.append("- Version: " + version())
    lines.append(
        "- Open tasks: P0=%d  P1=%d  P2=%d  P3=%d" % (c["P0"], c["P1"], c["P2"], c["P3"])
    )
    if pc is not None:
        lines.append("- Plans: active=%d  completed=%d" % (pc[0], pc[1]))
    lines.append("")
    lines.append("## Latest release notes")
    lines.append("")
    lines.append(latest_changelog_entry())
    lines.append("")
    lines.append("## Recent activity")
    lines.append("")
    lines.append(latest_activity())
    lines.append("")

    out = os.path.join(ROOT, "harness", "DASHBOARD.md")
    content = "\n".join(lines) + "\n"
    if _write_if_changed(out, content):
        print("dashboard: wrote harness/DASHBOARD.md (version %s, P0=%d)" % (version(), c["P0"]))
    else:
        print("dashboard: no substantive change; harness/DASHBOARD.md left as-is")


if __name__ == "__main__":
    main()
