import type { AgentRuntimeAdapter, GeneratedFile, StarterConfig } from "../types.js";

function agentsPackage(config: StarterConfig): string {
  const dependencies: Record<string, string> = {
    "@mastra/core": "^1.47.0",
    zod: "^4.4.3"
  };

  if (config.aiObservability === "langfuse") {
    dependencies["@mastra/langfuse"] = "^1.4.2";
  }

  if (config.telemetry === "opentelemetry") {
    dependencies["@opentelemetry/api"] = "^1.9.1";
  }

  if (config.workflowRuntime === "temporal") {
    dependencies["@temporalio/client"] = "^1.18.1";
  }

  return JSON.stringify(
    {
      name: `@qatar-navigation-milaha/${config.projectSlug}-agents`,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        build: "tsc -p tsconfig.build.json",
        lint: "eslint . --max-warnings 0",
        typecheck: "tsc --noEmit",
        test: "vitest --run",
        "test:coverage": "vitest --run --coverage",
        "eval:baseline": "tsx src/evals/baseline.ts",
        "governance:check": "tsx src/governance/check.ts"
      },
      dependencies,
      devDependencies: {
        "@eslint/js": "^9.39.1",
        "@types/node": "^22.19.1",
        "@vitest/coverage-v8": "^4.0.8",
        eslint: "^9.39.1",
        tsx: "^4.20.6",
        typescript: "^5.9.3",
        "typescript-eslint": "^8.46.4",
        vitest: "^4.0.8"
      }
    },
    null,
    2
  );
}

function langfuseFile(config: StarterConfig): GeneratedFile {
  if (config.aiObservability !== "langfuse") {
    return {
      path: "apps/agents/src/observability/langfuse.ts",
      content: `export function langfuseCredentialsPresent(env: Record<string, string | undefined> = {}) {
  void env;
  return false;
}

export function createObservabilityConfig(env: Record<string, string | undefined> = {}) {
  void env;
  return undefined;
}
`
    };
  }

  return {
    path: "apps/agents/src/observability/langfuse.ts",
    content: `import { LangfuseExporter } from "@mastra/langfuse";

export interface LangfuseEnv {
  LANGFUSE_PUBLIC_KEY?: string;
  LANGFUSE_SECRET_KEY?: string;
  LANGFUSE_BASE_URL?: string;
}

export function langfuseCredentialsPresent(env: LangfuseEnv = process.env) {
  return Boolean(env.LANGFUSE_PUBLIC_KEY && env.LANGFUSE_SECRET_KEY);
}

export function createObservabilityConfig(env: LangfuseEnv = process.env) {
  if (!langfuseCredentialsPresent(env)) {
    return undefined;
  }

  return {
    configs: {
      langfuse: {
        serviceName: "${config.projectSlug}-agents",
        exporters: [
          new LangfuseExporter({
            publicKey: env.LANGFUSE_PUBLIC_KEY,
            secretKey: env.LANGFUSE_SECRET_KEY,
            baseUrl: env.LANGFUSE_BASE_URL ?? "https://cloud.langfuse.com",
            environment: process.env.NODE_ENV ?? "development",
            release: process.env.GITHUB_SHA ?? "local"
          })
        ]
      }
    }
  };
}
`
  };
}

function temporalFiles(config: StarterConfig): GeneratedFile[] {
  if (config.workflowRuntime !== "temporal") {
    return [];
  }

  return [
    {
      path: "apps/agents/src/workflows/temporal.ts",
      content: `export const temporalWorkflowRuntime = {
  taskQueue: "${config.projectSlug}-agent-workflows",
  namespace: process.env.TEMPORAL_NAMESPACE ?? "default"
} as const;

export function temporalConfigured() {
  return Boolean(process.env.TEMPORAL_ADDRESS);
}
`
    },
    {
      path: "docs/templates/temporal-workflow-runbook-template.md",
      content: `# Temporal Workflow Runbook

## Workflow

- Name:
- Task queue: \`${config.projectSlug}-agent-workflows\`
- Owner:
- Rollback owner:

## Operations

- Start command:
- Retry policy:
- Alert route:
- Manual approval points:

## Evidence

- Workflow history link:
- Incident/change references:
- Last recovery drill:
`
    }
  ];
}

function mastraFiles(config: StarterConfig): GeneratedFile[] {
  if (config.agentRuntime !== "mastra") {
    return [];
  }

  return [
    {
      path: "apps/agents/package.json",
      content: `${agentsPackage(config)}\n`
    },
    {
      path: "apps/agents/README.md",
      content: `# ${config.projectName} Agents

Mastra AI runtime generated by \`milaha init\`.

The agent runtime is a replaceable orchestration layer. Keep authentication, authorization,
business rules, validation, audit logging, and approval decisions in \`apps/api\`.

## Commands

- \`pnpm lint\`
- \`pnpm typecheck\`
- \`pnpm test:coverage\`
- \`pnpm governance:check\`
- \`pnpm eval:baseline\`

## Runtime

- Agent runtime: Mastra AI
- AI observability: ${config.aiObservability === "langfuse" ? "Langfuse" : "None"}
- Telemetry: ${config.telemetry === "opentelemetry" ? "OpenTelemetry trace context" : "None"}
- Workflow runtime: ${config.workflowRuntime === "temporal" ? "Temporal" : "None"}

Set real model/provider credentials only after architecture review and model approval.
`
    },
    {
      path: "apps/agents/.env.example",
      content: `MASTRA_MODEL=openai/gpt-5
${config.aiObservability === "langfuse" ? "LANGFUSE_PUBLIC_KEY=pk-lf-example\nLANGFUSE_SECRET_KEY=sk-lf-example\nLANGFUSE_BASE_URL=https://cloud.langfuse.com\n" : ""}${config.workflowRuntime === "temporal" ? "TEMPORAL_ADDRESS=localhost:7233\nTEMPORAL_NAMESPACE=default\n" : ""}`
    },
    {
      path: "apps/agents/tsconfig.json",
      content: `{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "lib": ["ES2022"],
    "declaration": true,
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts", "vitest.config.ts", "eslint.config.mjs"]
}
`
    },
    {
      path: "apps/agents/tsconfig.build.json",
      content: `{
  "extends": "./tsconfig.json",
  "exclude": ["src/**/*.test.ts"]
}
`
    },
    {
      path: "apps/agents/eslint.config.mjs",
      content: `import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname
      }
    }
  }
);
`
    },
    {
      path: "apps/agents/vitest.config.ts",
      content: `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/governance/**/*.ts",
        "src/observability/**/*.ts",
        "src/evals/**/*.ts"
      ],
      exclude: ["src/governance/check.ts"],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100
      }
    }
  }
});
`
    },
    {
      path: "apps/agents/src/governance/tool-policy.ts",
      content: `export type ToolSideEffectLevel = "none" | "read" | "write" | "irreversible";

export interface AgentToolPolicy {
  id: string;
  owner: string;
  allowedScopes: string[];
  sideEffectLevel: ToolSideEffectLevel;
  humanApprovalRequired: boolean;
  dataClassification: "public" | "internal" | "confidential" | "restricted";
}

export const agentToolPolicies = [
  {
    id: "service-health",
    owner: "platform-engineering",
    allowedScopes: ["health:read"],
    sideEffectLevel: "read",
    humanApprovalRequired: false,
    dataClassification: "internal"
  },
  {
    id: "sensitive-action",
    owner: "platform-engineering",
    allowedScopes: ["agent:approve"],
    sideEffectLevel: "write",
    humanApprovalRequired: true,
    dataClassification: "restricted"
  }
] as const satisfies readonly AgentToolPolicy[];

export function findToolPolicy(toolId: string) {
  return agentToolPolicies.find((tool) => tool.id === toolId);
}

export function assertToolAllowed(toolId: string) {
  const policy = findToolPolicy(toolId);

  if (!policy) {
    throw new Error(\`Agent tool "\${toolId}" is not registered in the governance policy.\`);
  }

  return policy;
}

export function humanApprovalToolIds() {
  return agentToolPolicies
    .filter((tool) => tool.humanApprovalRequired)
    .map((tool) => tool.id);
}
`
    },
    {
      path: "apps/agents/src/tools/service-health.ts",
      content: `import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import { assertToolAllowed } from "../governance/tool-policy.js";

export const serviceHealthToolPolicy = assertToolAllowed("service-health");

export function buildServiceHealthResponse(input: { correlationId: string; service: string }) {
  return {
    status: "ok" as const,
    service: input.service,
    correlationId: input.correlationId,
    sideEffectLevel: serviceHealthToolPolicy.sideEffectLevel
  };
}

export const serviceHealthTool = createTool({
  id: serviceHealthToolPolicy.id,
  description: "Read-only health check through the governed API boundary.",
  inputSchema: z.object({
    correlationId: z.string().min(1),
    service: z.string().min(1).default("${config.projectSlug}")
  }),
  outputSchema: z.object({
    status: z.literal("ok"),
    service: z.string(),
    correlationId: z.string(),
    sideEffectLevel: z.literal("read")
  }),
  execute: async (input) => buildServiceHealthResponse(input)
});
`
    },
    {
      path: "apps/agents/src/agents/operations-agent.ts",
      content: `import { Agent } from "@mastra/core/agent";
import { serviceHealthTool } from "../tools/service-health.js";

export const operationsAgent = new Agent({
  id: "${config.projectSlug}-operations-agent",
  name: "${config.projectName} Operations Agent",
  instructions: [
    "You operate inside the Milaha governed-agent baseline.",
    "Call only tools registered in the governance policy.",
    "Never bypass apps/api for authentication, authorization, validation, audit, or approvals.",
    "Return structured, traceable responses with correlation IDs."
  ].join("\\n"),
  model: process.env.MASTRA_MODEL ?? "openai/gpt-5",
  tools: {
    serviceHealth: serviceHealthTool
  }
});
`
    },
    {
      path: "apps/agents/src/observability/trace-policy.ts",
      content: `export const requiredTraceTags = [
  "milaha.project",
  "milaha.agent_runtime",
  "milaha.agent_id",
  "milaha.tool_id",
  "milaha.correlation_id",
  "milaha.data_classification"
] as const;

export type RequiredTraceTag = (typeof requiredTraceTags)[number];

export function buildTraceTags(input: {
  agentId: string;
  toolId: string;
  correlationId: string;
  dataClassification: string;
}) {
  return {
    "milaha.project": "${config.projectSlug}",
    "milaha.agent_runtime": "mastra",
    "milaha.agent_id": input.agentId,
    "milaha.tool_id": input.toolId,
    "milaha.correlation_id": input.correlationId,
    "milaha.data_classification": input.dataClassification
  } satisfies Record<RequiredTraceTag, string>;
}

export function missingTraceTags(tags: Record<string, string>) {
  return requiredTraceTags.filter((tag) => !tags[tag]);
}
`
    },
    langfuseFile(config),
    {
      path: "apps/agents/src/evals/baseline.ts",
      content: `export interface BaselineEvaluationPlan {
  dataset: string;
  minimumPassingScore: number;
  checks: readonly string[];
}

export const baselineEvaluationPlan = {
  dataset: "${config.projectSlug}-agent-baseline",
  minimumPassingScore: 1,
  checks: [
    "tool calls use registered policies",
    "responses include correlation IDs",
    "restricted data is not exposed",
    "human approval is requested for sensitive actions"
  ]
} as const satisfies BaselineEvaluationPlan;

export function baselineEvaluationReady(plan: BaselineEvaluationPlan = baselineEvaluationPlan) {
  return plan.checks.length >= 4 && plan.minimumPassingScore === 1;
}

/* v8 ignore next 4 */
if (process.argv[1]?.endsWith("baseline.ts") && !baselineEvaluationReady()) {
  console.error("Baseline evaluation plan is incomplete.");
  process.exitCode = 1;
}
`
    },
    {
      path: "apps/agents/src/governance/check.ts",
      content: `import { pathToFileURL } from "node:url";
import { baselineEvaluationReady } from "../evals/baseline.js";
import { buildTraceTags, missingTraceTags } from "../observability/trace-policy.js";
import { agentToolPolicies } from "./tool-policy.js";

export function validateGovernanceBaseline() {
  const issues: string[] = [];

  if (agentToolPolicies.length === 0) {
    issues.push("At least one governed agent tool policy is required.");
  }

  for (const tool of agentToolPolicies) {
    if (tool.allowedScopes.length === 0) {
      issues.push(\`Tool "\${tool.id}" must declare at least one allowed scope.\`);
    }
  }

  const traceTags = buildTraceTags({
    agentId: "${config.projectSlug}-operations-agent",
    toolId: "service-health",
    correlationId: "governance-check",
    dataClassification: "internal"
  });
  const missing = missingTraceTags(traceTags);

  if (missing.length > 0) {
    issues.push(\`Missing trace tags: \${missing.join(", ")}\`);
  }

  if (!baselineEvaluationReady()) {
    issues.push("Baseline evaluation plan is incomplete.");
  }

  return issues;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const issues = validateGovernanceBaseline();

  if (issues.length > 0) {
    console.error(issues.join("\\n"));
    process.exitCode = 1;
  }
}
`
    },
    {
      path: "apps/agents/src/mastra.ts",
      content: `import { Mastra } from "@mastra/core/mastra";
import { operationsAgent } from "./agents/operations-agent.js";
import { createObservabilityConfig } from "./observability/langfuse.js";

export function createMastraRuntime() {
  const observability = createObservabilityConfig();

  return new Mastra({
    agents: {
      operationsAgent
    },
    ...(observability ? { observability } : {})
  });
}

export const mastra = createMastraRuntime();
`
    },
    {
      path: "apps/agents/src/index.ts",
      content: `export { mastra, createMastraRuntime } from "./mastra.js";
export { operationsAgent } from "./agents/operations-agent.js";
export { agentToolPolicies } from "./governance/tool-policy.js";
`
    },
    {
      path: "apps/agents/src/governance/tool-policy.test.ts",
      content: `import { describe, expect, it } from "vitest";
import { assertToolAllowed, findToolPolicy, humanApprovalToolIds } from "./tool-policy.js";

describe("agent tool governance policy", () => {
  it("registers the service health tool as read-only", () => {
    expect(findToolPolicy("service-health")).toMatchObject({
      sideEffectLevel: "read",
      humanApprovalRequired: false,
      dataClassification: "internal"
    });
  });

  it("rejects tools outside the registry", () => {
    expect(() => assertToolAllowed("unregistered")).toThrow(/not registered/);
  });

  it("lists tools that require human approval", () => {
    expect(humanApprovalToolIds()).toEqual(["sensitive-action"]);
  });
});
`
    },
    {
      path: "apps/agents/src/observability/trace-policy.test.ts",
      content: `import { describe, expect, it } from "vitest";
import { buildTraceTags, missingTraceTags, requiredTraceTags } from "./trace-policy.js";

describe("trace policy", () => {
  it("builds the required Milaha trace tags", () => {
    const tags = buildTraceTags({
      agentId: "agent",
      toolId: "tool",
      correlationId: "corr",
      dataClassification: "internal"
    });

    expect(missingTraceTags(tags)).toEqual([]);
    expect(Object.keys(tags)).toEqual([...requiredTraceTags]);
  });

  it("reports missing required tags", () => {
    expect(missingTraceTags({ "milaha.project": "demo" })).toContain("milaha.agent_runtime");
  });
});
`
    },
    {
      path: "apps/agents/src/observability/langfuse.test.ts",
      content: `import { describe, expect, it } from "vitest";
import { createObservabilityConfig, langfuseCredentialsPresent } from "./langfuse.js";

describe("Langfuse observability config", () => {
  it("requires Langfuse credentials before enabling the exporter", () => {
    expect(langfuseCredentialsPresent({})).toBe(${config.aiObservability === "langfuse" ? "false" : "false"});
    expect(createObservabilityConfig({})).toBeUndefined();
  });

  it("creates config when credentials are provided", () => {
    const config = createObservabilityConfig({
      LANGFUSE_PUBLIC_KEY: "pk-lf-example",
      LANGFUSE_SECRET_KEY: "sk-lf-example"
    });

    expect(config).${config.aiObservability === "langfuse" ? "toBeDefined()" : "toBeUndefined()"};
  });
});
`
    },
    {
      path: "apps/agents/src/evals/baseline.test.ts",
      content: `import { describe, expect, it } from "vitest";
import { baselineEvaluationPlan, baselineEvaluationReady } from "./baseline.js";

describe("baseline evaluation plan", () => {
  it("requires policy, traceability, data, and approval checks", () => {
    expect(baselineEvaluationReady()).toBe(true);
    expect(baselineEvaluationPlan.checks).toContain("tool calls use registered policies");
  });

  it("rejects incomplete plans", () => {
    expect(
      baselineEvaluationReady({
        ...baselineEvaluationPlan,
        checks: ["tool calls use registered policies"]
      })
    ).toBe(false);
  });
});
`
    },
    ...temporalFiles(config)
  ];
}

export const agentRuntimeAdapters: Record<string, AgentRuntimeAdapter> = {
  none: {
    id: "none",
    label: "No agent runtime",
    files() {
      return [];
    }
  },
  mastra: {
    id: "mastra",
    label: "Mastra AI",
    files: mastraFiles
  }
};
