import type { BackendAdapter, GeneratedFile, StarterConfig } from "../types.js";

function openApiContractObject(config: StarterConfig) {
  return {
    openapi: "3.1.0",
    info: {
      title: `${config.projectName} API`,
      version: "0.1.0",
      description: config.projectOneLiner
    },
    paths: {
      "/health": {
        get: {
          operationId: "getHealth",
          tags: ["health"],
          responses: {
            "200": {
              description: "Service health response"
            }
          }
        }
      }
    }
  };
}

function nestPackage(config: StarterConfig): string {
  return JSON.stringify(
    {
      name: `@qatar-navigation-milaha/${config.projectSlug}-api`,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        build: "tsc -p tsconfig.build.json",
        lint: "eslint . --max-warnings 0",
        typecheck: "tsc --noEmit",
        test: "vitest --run",
        "test:coverage": "vitest --run --coverage",
        start: "node dist/main.js",
        dev: "tsx watch src/main.ts",
        "openapi:generate": "tsx src/openapi.ts",
        "openapi:check": "tsx src/openapi.ts --check"
      },
      dependencies: {
        "@nestjs/common": "^11.1.6",
        "@nestjs/core": "^11.1.6",
        "@nestjs/platform-express": "^11.1.6",
        "@nestjs/swagger": "^11.2.3",
        ...(config.telemetry === "opentelemetry" ? { "@opentelemetry/api": "^1.9.1" } : {}),
        "reflect-metadata": "^0.2.2",
        rxjs: "^7.8.2"
      },
      devDependencies: {
        "@eslint/js": "^9.39.1",
        "@types/node": "^22.19.1",
        "@vitest/coverage-v8": "^4.0.8",
        eslint: "^9.39.1",
        tsx: "^4.20.6",
        typescript: "^5.9.3",
        "typescript-eslint": "^8.46.4",
        vitest: "^4.0.8"
      }
    },
    null,
    2
  );
}

function nestFiles(config: StarterConfig): GeneratedFile[] {
  return [
    {
      path: "apps/api/package.json",
      content: `${nestPackage(config)}\n`
    },
    {
      path: "apps/api/README.md",
      content: `# ${config.projectName} API\n\nNestJS service generated by \`milaha init\`.\n\n## Commands\n\n- \`pnpm lint\`\n- \`pnpm typecheck\`\n- \`pnpm test:coverage\`\n\nCoverage is enforced at 100% for project-owned code.\n`
    },
    {
      path: "apps/api/tsconfig.json",
      content: `{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "lib": ["ES2022"],
    "declaration": true,
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts", "vitest.config.ts", "eslint.config.mjs"]
}
`
    },
    {
      path: "apps/api/tsconfig.build.json",
      content: `{
  "extends": "./tsconfig.json",
  "exclude": ["src/**/*.spec.ts"]
}
`
    },
    {
      path: "apps/api/eslint.config.mjs",
      content: `import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname
      }
    }
  }
);
`
    },
    {
      path: "apps/api/vitest.config.ts",
      content: `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.spec.ts"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      exclude: [
        "src/main.ts",
        "src/openapi.ts",
        "src/governance/trace-context.ts",
        "src/**/*.module.ts",
        "src/**/*.spec.ts"
      ],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100
      }
    }
  }
});
`
    },
    {
      path: "apps/api/src/main.ts",
      content: `import "reflect-metadata";
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module.js";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(process.env.PORT ? Number(process.env.PORT) : 3000);
}

void bootstrap();
`
    },
    {
      path: "apps/api/src/app.module.ts",
      content: `import { Module } from "@nestjs/common";
import { HealthController } from "./health.controller.js";

@Module({
  controllers: [HealthController]
})
export class AppModule {}
`
    },
    {
      path: "apps/api/src/health.controller.ts",
      content: `import { Controller, Get } from "@nestjs/common";

@Controller("health")
export class HealthController {
  @Get()
  check() {
    return {
      status: "ok",
      service: "${config.projectSlug}"
    };
  }
}
`
    },
    {
      path: "apps/api/src/health.controller.spec.ts",
      content: `import { describe, expect, it } from "vitest";
import { HealthController } from "./health.controller.js";

describe("HealthController", () => {
  it("returns service health", () => {
    expect(new HealthController().check()).toEqual({
      status: "ok",
      service: "${config.projectSlug}"
    });
  });
});
`
    },
    {
      path: "apps/api/src/governance/rbac.ts",
      content: `export type ApiScope = "health:read";

export const routeScopeMap = {
  "GET /health": ["health:read"]
} as const satisfies Record<string, readonly ApiScope[]>;

export function scopesForRoute(route: keyof typeof routeScopeMap) {
  return routeScopeMap[route];
}

export function hasRequiredScope(userScopes: readonly string[], requiredScope: ApiScope) {
  return userScopes.includes(requiredScope);
}
`
    },
    {
      path: "apps/api/src/governance/audit.ts",
      content: `export interface AuditEventInput {
  actorId: string;
  action: string;
  resource: string;
  correlationId: string;
}

export function createAuditEvent(input: AuditEventInput) {
  return {
    ...input,
    source: "${config.projectSlug}-api",
    schemaVersion: "2026-06-27",
    emittedAt: new Date(0).toISOString()
  };
}
`
    },
    {
      path: "apps/api/src/governance/trace-context.ts",
      content:
        config.telemetry === "opentelemetry"
          ? `import { trace } from "@opentelemetry/api";

export function currentTraceId() {
  return trace.getActiveSpan()?.spanContext().traceId ?? "untraced";
}
`
          : `export function currentTraceId() {
  return "untraced";
}
`
    },
    {
      path: "apps/api/src/governance/governance.spec.ts",
      content: `import { describe, expect, it } from "vitest";
import { createAuditEvent } from "./audit.js";
import { hasRequiredScope, scopesForRoute } from "./rbac.js";
import { currentTraceId } from "./trace-context.js";

describe("API governance boundary", () => {
  it("maps routes to API scopes", () => {
    expect(scopesForRoute("GET /health")).toEqual(["health:read"]);
    expect(hasRequiredScope(["health:read"], "health:read")).toBe(true);
  });

  it("creates SIEM-shaped audit events", () => {
    expect(
      createAuditEvent({
        actorId: "system",
        action: "health.check",
        resource: "health",
        correlationId: "corr-1"
      })
    ).toMatchObject({
      source: "${config.projectSlug}-api",
      schemaVersion: "2026-06-27",
      correlationId: "corr-1"
    });
  });

  it("provides a trace fallback for local execution", () => {
    expect(currentTraceId()).toBe("untraced");
  });
});
`
    },
    {
      path: "apps/api/src/openapi.ts",
      content: `import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

export const openApiContract = ${JSON.stringify(openApiContractObject(config), null, 2)} as const;

export function openApiContractPath() {
  return path.resolve(process.cwd(), "../../contracts/openapi/api.json");
}

export async function writeOpenApiContract() {
  const target = openApiContractPath();
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, JSON.stringify(openApiContract, null, 2) + "\\n");
}

export async function checkOpenApiContract() {
  const expected = JSON.stringify(openApiContract, null, 2) + "\\n";
  const current = await fs.readFile(openApiContractPath(), "utf8");
  return current === expected;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes("--check")) {
    const ok = await checkOpenApiContract();

    if (!ok) {
      console.error("OpenAPI contract is out of date. Run pnpm openapi:generate.");
      process.exitCode = 1;
    }
  } else {
    await writeOpenApiContract();
  }
}
`
    }
  ];
}

function fastApiFiles(config: StarterConfig): GeneratedFile[] {
  return [
    {
      path: "apps/api/.python-version",
      content: "3.12\n"
    },
    {
      path: "apps/api/README.md",
      content: `# ${config.projectName} API\n\nFastAPI service generated by \`milaha init\`.\n\n## Commands\n\n- \`uv run ruff format --check .\`\n- \`uv run ruff check .\`\n- \`uv run mypy app tests\`\n- \`uv run pytest --cov=app --cov-report=term-missing --cov-fail-under=100\`\n\nCoverage is enforced at 100% for project-owned code.\n`
    },
    {
      path: "apps/api/pyproject.toml",
      content: `[project]
name = "${config.projectSlug}-api"
version = "0.1.0"
description = "${config.projectOneLiner}"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.0",
${config.telemetry === "opentelemetry" ? '  "opentelemetry-api>=1.29.0",\n' : ""}  "uvicorn[standard]>=0.34.0"
]

[dependency-groups]
dev = [
  "bandit>=1.8.0",
  "httpx>=0.28.0",
  "mypy>=1.14.0",
  "pip-audit>=2.7.0",
  "pytest>=8.3.0",
  "pytest-cov>=6.0.0",
  "ruff>=0.9.0"
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "S"]
ignore = ["S101"]

[tool.mypy]
python_version = "3.12"
strict = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=app --cov-report=term-missing --cov-fail-under=100"

[tool.coverage.run]
source = ["app"]
omit = ["app/__init__.py", "app/openapi.py", "app/governance/trace_context.py"]

[tool.coverage.report]
fail_under = 100
show_missing = true
`
    },
    {
      path: "apps/api/app/__init__.py",
      content: ""
    },
    {
      path: "apps/api/app/main.py",
      content: `from fastapi import FastAPI

from app.openapi import build_openapi_contract

app = FastAPI(
    title="${config.projectName} API",
    version="0.1.0",
    description="${config.projectOneLiner}",
)


def custom_openapi() -> dict[str, object]:
    return build_openapi_contract()


app.openapi = custom_openapi  # type: ignore[method-assign]


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "${config.projectSlug}"}
`
    },
    {
      path: "apps/api/app/openapi.py",
      content: `def build_openapi_contract() -> dict[str, object]:
    return ${JSON.stringify(openApiContractObject(config), null, 4).replace(/\n/g, "\n    ")}
`
    },
    {
      path: "apps/api/app/governance/__init__.py",
      content: ""
    },
    {
      path: "apps/api/app/governance/rbac.py",
      content: `from typing import Literal

ApiScope = Literal["health:read"]

ROUTE_SCOPE_MAP: dict[str, tuple[ApiScope, ...]] = {
    "GET /health": ("health:read",),
}


def scopes_for_route(route: str) -> tuple[ApiScope, ...]:
    return ROUTE_SCOPE_MAP[route]


def has_required_scope(user_scopes: tuple[str, ...], required_scope: ApiScope) -> bool:
    return required_scope in user_scopes
`
    },
    {
      path: "apps/api/app/governance/audit.py",
      content: `from dataclasses import dataclass


@dataclass(frozen=True)
class AuditEventInput:
    actor_id: str
    action: str
    resource: str
    correlation_id: str


def create_audit_event(event: AuditEventInput) -> dict[str, str]:
    return {
        "actor_id": event.actor_id,
        "action": event.action,
        "resource": event.resource,
        "correlation_id": event.correlation_id,
        "source": "${config.projectSlug}-api",
        "schema_version": "2026-06-27",
        "emitted_at": "1970-01-01T00:00:00+00:00",
    }
`
    },
    {
      path: "apps/api/app/governance/trace_context.py",
      content:
        config.telemetry === "opentelemetry"
          ? `from opentelemetry import trace


def current_trace_id() -> str:
    span_context = trace.get_current_span().get_span_context()
    if not span_context.is_valid:
        return "untraced"
    return format(span_context.trace_id, "032x")
`
          : `def current_trace_id() -> str:
    return "untraced"
`
    },
    {
      path: "apps/api/scripts/export_openapi.py",
      content: `import json
import sys
from pathlib import Path

from app.main import app


def contract_path() -> Path:
    return Path(__file__).resolve().parents[3] / "contracts" / "openapi" / "api.json"


def rendered_contract() -> str:
    return json.dumps(app.openapi(), indent=2) + "\\n"


def write_contract() -> None:
    target = contract_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered_contract(), encoding="utf-8")


def check_contract() -> bool:
    return contract_path().read_text(encoding="utf-8") == rendered_contract()


if __name__ == "__main__":
    if "--check" in sys.argv:
        if not check_contract():
            print("OpenAPI contract is out of date. Run uv run python scripts/export_openapi.py.")
            raise SystemExit(1)
    else:
        write_contract()
`
    },
    {
      path: "apps/api/tests/test_health.py",
      content: `from fastapi.testclient import TestClient

from app.main import app


def test_health_endpoint() -> None:
    response = TestClient(app).get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "service": "${config.projectSlug}"}


def test_openapi_contract_is_customized() -> None:
    contract = app.openapi()

    assert contract["info"]["title"] == "${config.projectName} API"
    assert contract["paths"]["/health"]["get"]["operationId"] == "getHealth"
`
    },
    {
      path: "apps/api/tests/test_governance.py",
      content: `from app.governance.audit import AuditEventInput, create_audit_event
from app.governance.rbac import has_required_scope, scopes_for_route
from app.governance.trace_context import current_trace_id


def test_route_scopes() -> None:
    assert scopes_for_route("GET /health") == ("health:read",)
    assert has_required_scope(("health:read",), "health:read") is True


def test_audit_event_shape() -> None:
    event = create_audit_event(
        AuditEventInput(
            actor_id="system",
            action="health.check",
            resource="health",
            correlation_id="corr-1",
        )
    )

    assert event["source"] == "${config.projectSlug}-api"
    assert event["schema_version"] == "2026-06-27"
    assert event["correlation_id"] == "corr-1"


def test_trace_fallback() -> None:
    assert current_trace_id() == "untraced"
`
    }
  ];
}

export const backendAdapters: Record<string, BackendAdapter> = {
  nestjs: {
    id: "nestjs",
    label: "NestJS (TypeScript)",
    primaryLanguage: "TypeScript",
    externalCommand(config) {
      return {
        command: "pnpm",
        args: [
          "dlx",
          "@nestjs/cli",
          "new",
          "api",
          "--directory",
          "apps/api",
          "--package-manager",
          "pnpm",
          "--skip-git",
          "--skip-install",
          "--strict"
        ],
        cwd: config.targetDir,
        description: "NestJS official project generator"
      };
    },
    files: nestFiles
  },
  fastapi: {
    id: "fastapi",
    label: "FastAPI (Python)",
    primaryLanguage: "Python",
    externalCommand() {
      return null;
    },
    files: fastApiFiles
  }
};
