import type { BackendAdapter, GeneratedFile, StarterConfig } from "../types.js";

function nestPackage(config: StarterConfig): string {
  return JSON.stringify(
    {
      name: `@qatar-navigation-milaha/${config.projectSlug}-api`,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        build: "tsc -p tsconfig.build.json",
        lint: "eslint . --max-warnings 0",
        typecheck: "tsc --noEmit",
        test: "vitest --run",
        "test:coverage": "vitest --run --coverage",
        start: "node dist/main.js",
        dev: "tsx watch src/main.ts"
      },
      dependencies: {
        "@nestjs/common": "^11.1.6",
        "@nestjs/core": "^11.1.6",
        "@nestjs/platform-express": "^11.1.6",
        "reflect-metadata": "^0.2.2",
        rxjs: "^7.8.2"
      },
      devDependencies: {
        "@eslint/js": "^9.39.1",
        "@types/node": "^22.19.1",
        "@vitest/coverage-v8": "^4.0.8",
        eslint: "^9.39.1",
        tsx: "^4.20.6",
        typescript: "^5.9.3",
        "typescript-eslint": "^8.46.4",
        vitest: "^4.0.8"
      }
    },
    null,
    2
  );
}

function nestFiles(config: StarterConfig): GeneratedFile[] {
  return [
    {
      path: "apps/api/package.json",
      content: `${nestPackage(config)}\n`
    },
    {
      path: "apps/api/README.md",
      content: `# ${config.projectName} API\n\nNestJS service generated by \`milaha init\`.\n\n## Commands\n\n- \`pnpm lint\`\n- \`pnpm typecheck\`\n- \`pnpm test:coverage\`\n\nCoverage is enforced at 100% for project-owned code.\n`
    },
    {
      path: "apps/api/tsconfig.json",
      content: `{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "lib": ["ES2022"],
    "declaration": true,
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts", "vitest.config.ts", "eslint.config.mjs"]
}
`
    },
    {
      path: "apps/api/tsconfig.build.json",
      content: `{
  "extends": "./tsconfig.json",
  "exclude": ["src/**/*.spec.ts"]
}
`
    },
    {
      path: "apps/api/eslint.config.mjs",
      content: `import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname
      }
    }
  }
);
`
    },
    {
      path: "apps/api/vitest.config.ts",
      content: `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.spec.ts"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      exclude: ["src/main.ts", "src/**/*.module.ts", "src/**/*.spec.ts"],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100
      }
    }
  }
});
`
    },
    {
      path: "apps/api/src/main.ts",
      content: `import "reflect-metadata";
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module.js";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(process.env.PORT ? Number(process.env.PORT) : 3000);
}

void bootstrap();
`
    },
    {
      path: "apps/api/src/app.module.ts",
      content: `import { Module } from "@nestjs/common";
import { HealthController } from "./health.controller.js";

@Module({
  controllers: [HealthController]
})
export class AppModule {}
`
    },
    {
      path: "apps/api/src/health.controller.ts",
      content: `import { Controller, Get } from "@nestjs/common";

@Controller("health")
export class HealthController {
  @Get()
  check() {
    return {
      status: "ok",
      service: "${config.projectSlug}"
    };
  }
}
`
    },
    {
      path: "apps/api/src/health.controller.spec.ts",
      content: `import { describe, expect, it } from "vitest";
import { HealthController } from "./health.controller.js";

describe("HealthController", () => {
  it("returns service health", () => {
    expect(new HealthController().check()).toEqual({
      status: "ok",
      service: "${config.projectSlug}"
    });
  });
});
`
    }
  ];
}

function fastApiFiles(config: StarterConfig): GeneratedFile[] {
  return [
    {
      path: "apps/api/.python-version",
      content: "3.12\n"
    },
    {
      path: "apps/api/README.md",
      content: `# ${config.projectName} API\n\nFastAPI service generated by \`milaha init\`.\n\n## Commands\n\n- \`uv run ruff format --check .\`\n- \`uv run ruff check .\`\n- \`uv run mypy app tests\`\n- \`uv run pytest --cov=app --cov-report=term-missing --cov-fail-under=100\`\n\nCoverage is enforced at 100% for project-owned code.\n`
    },
    {
      path: "apps/api/pyproject.toml",
      content: `[project]
name = "${config.projectSlug}-api"
version = "0.1.0"
description = "${config.projectOneLiner}"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.34.0"
]

[dependency-groups]
dev = [
  "bandit>=1.8.0",
  "httpx>=0.28.0",
  "mypy>=1.14.0",
  "pip-audit>=2.7.0",
  "pytest>=8.3.0",
  "pytest-cov>=6.0.0",
  "ruff>=0.9.0"
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "S"]
ignore = ["S101"]

[tool.mypy]
python_version = "3.12"
strict = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=app --cov-report=term-missing --cov-fail-under=100"

[tool.coverage.run]
source = ["app"]
omit = ["app/__init__.py"]

[tool.coverage.report]
fail_under = 100
show_missing = true
`
    },
    {
      path: "apps/api/app/__init__.py",
      content: ""
    },
    {
      path: "apps/api/app/main.py",
      content: `from fastapi import FastAPI

app = FastAPI(title="${config.projectName} API")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "${config.projectSlug}"}
`
    },
    {
      path: "apps/api/tests/test_health.py",
      content: `from fastapi.testclient import TestClient

from app.main import app


def test_health_endpoint() -> None:
    response = TestClient(app).get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "service": "${config.projectSlug}"}
`
    }
  ];
}

export const backendAdapters: Record<string, BackendAdapter> = {
  nestjs: {
    id: "nestjs",
    label: "NestJS (TypeScript)",
    primaryLanguage: "TypeScript",
    externalCommand(config) {
      return {
        command: "pnpm",
        args: [
          "dlx",
          "@nestjs/cli",
          "new",
          "api",
          "--directory",
          "apps/api",
          "--package-manager",
          "pnpm",
          "--skip-git",
          "--skip-install",
          "--strict"
        ],
        cwd: config.targetDir,
        description: "NestJS official project generator"
      };
    },
    files: nestFiles
  },
  fastapi: {
    id: "fastapi",
    label: "FastAPI (Python)",
    primaryLanguage: "Python",
    externalCommand() {
      return null;
    },
    files: fastApiFiles
  }
};
