import type { FrontendAdapter, GeneratedFile, StarterConfig } from "../types.js";

function nextFiles(config: StarterConfig): GeneratedFile[] {
  if (config.frontend === "none") {
    return [];
  }

  return [
    {
      path: "apps/web/package.json",
      content: `${JSON.stringify(
        {
          name: `@qatar-navigation-milaha/${config.projectSlug}-web`,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "eslint . --max-warnings 0",
            typecheck: "tsc --noEmit",
            test: "vitest --run",
            "test:coverage": "vitest --run --coverage"
          },
          dependencies: {
            "@qatar-navigation-milaha/ui": "^0.2.0",
            next: "^16.0.4",
            react: "^19.2.0",
            "react-dom": "^19.2.0"
          },
          devDependencies: {
            "@eslint/js": "^9.39.1",
            "@testing-library/jest-dom": "^6.9.1",
            "@testing-library/react": "^16.3.0",
            "@types/node": "^22.19.1",
            "@types/react": "^19.2.6",
            "@types/react-dom": "^19.2.3",
            "@vitejs/plugin-react": "^5.1.1",
            "@vitest/coverage-v8": "^4.0.8",
            eslint: "^9.39.1",
            jsdom: "^27.2.0",
            tailwindcss: "^3.4.17",
            typescript: "^5.9.3",
            "typescript-eslint": "^8.46.4",
            vite: "^7.2.4",
            vitest: "^4.0.8"
          }
        },
        null,
        2
      )}\n`
    },
    {
      path: "apps/web/README.md",
      content: `# ${config.projectName} Web\n\nNext.js frontend generated by \`milaha init\` and wired for the Milaha UI package.\n`
    },
    {
      path: "apps/web/tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`
    },
    {
      path: "apps/web/next-env.d.ts",
      content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`
    },
    {
      path: "apps/web/next.config.mjs",
      content: `/** @type {import("next").NextConfig} */
const nextConfig = {};

export default nextConfig;
`
    },
    {
      path: "apps/web/postcss.config.mjs",
      content: `export default {
  plugins: {
    tailwindcss: {}
  }
};
`
    },
    {
      path: "apps/web/tailwind.config.ts",
      content: `import type { Config } from "tailwindcss";
import milahaPreset from "@qatar-navigation-milaha/ui/tailwind-preset";

export default {
  presets: [milahaPreset],
  content: ["./src/**/*.{ts,tsx}", "../../node_modules/@qatar-navigation-milaha/ui/dist/**/*.js"]
} satisfies Config;
`
    },
    {
      path: "apps/web/eslint.config.mjs",
      content: `import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(js.configs.recommended, ...tseslint.configs.strict, {
  files: ["src/**/*.{ts,tsx}"]
});
`
    },
    {
      path: "apps/web/vitest.config.ts",
      content: `import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.tsx"],
    setupFiles: ["src/test/setup.ts"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.{ts,tsx}"],
      exclude: ["src/test/**", "src/**/*.test.tsx", "src/app/layout.tsx"],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100
      }
    }
  }
});
`
    },
    {
      path: "apps/web/src/test/setup.ts",
      content: `import "@testing-library/jest-dom/vitest";
`
    },
    {
      path: "apps/web/src/app/globals.css",
      content: `@import "@qatar-navigation-milaha/ui/styles.css";

@tailwind base;
@tailwind components;
@tailwind utilities;
`
    },
    {
      path: "apps/web/src/app/layout.tsx",
      content: `import "./globals.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "${config.projectName}"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
    },
    {
      path: "apps/web/src/app/page.tsx",
      content: `import { getProjectLabel } from "../lib/project.js";

export default function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col justify-center px-6">
      <p className="text-sm font-semibold uppercase text-primary">Milaha Starter</p>
      <h1 className="mt-3 text-4xl font-bold text-text">{getProjectLabel()}</h1>
      <p className="mt-4 text-lg text-muted-foreground">${config.projectOneLiner}</p>
    </main>
  );
}
`
    },
    {
      path: "apps/web/src/lib/project.ts",
      content: `export function getProjectLabel() {
  return "${config.projectName}";
}
`
    },
    {
      path: "apps/web/src/lib/project.test.tsx",
      content: `import { describe, expect, it } from "vitest";
import { getProjectLabel } from "./project.js";

describe("getProjectLabel", () => {
  it("returns the configured project name", () => {
    expect(getProjectLabel()).toBe("${config.projectName}");
  });
});
`
    }
  ];
}

export const frontendAdapters: Record<string, FrontendAdapter> = {
  none: {
    id: "none",
    label: "No frontend",
    externalCommand() {
      return null;
    },
    files() {
      return [];
    }
  },
  nextjs: {
    id: "nextjs",
    label: "Next.js / React",
    externalCommand(config) {
      return {
        command: "pnpm",
        args: [
          "dlx",
          "create-next-app@latest",
          "apps/web",
          "--ts",
          "--tailwind",
          "--eslint",
          "--app",
          "--src-dir",
          "--use-pnpm",
          "--yes"
        ],
        cwd: config.targetDir,
        description: "Next.js official project generator"
      };
    },
    files: nextFiles
  }
};
